# Your bot token. If you don't know how to get it, watch this video: https://www.youtube.com/watch?v=aI4OmIbkJH8
bot-token: ""
# The guild where the bot will send the embed
guild-id: ""
# The channel that will be used to send the embed
channel-id: ""

# How many seconds the bot will wait to update the message
update-interval: 120

# Embeds, feel free to personalize them!

# Placeholders:
# %time% -> The time in HH:mm:ss format
# %date% -> The date in dd/MM/yyyy format
# %date-us% -> The date in MM/dd/yyyy format
# %player_count% -> The number of players online
# %max_players% -> The maximum number of players that can be online
# %players_list% -> The server's players list

# Use \n to skip a line
# Embeds also support markdown, which you can use to format the text. If you want to learn more about markdown, check this link: https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51
# All colors should be in HEX format, like: #7edb64

online-embed:
  title: "Server Status"
  timestamp: false
  color: "#7edb64"
  fields:
    - name: "> **Status**"
      value: "```fix\nOnline```"
      inline: true
    - name: "> **Players**"
      value: "```cs\n%player_count%```"
      inline: true
    - name: "IP:"
      value: "```prolog\nONEWAYCRAFT.NET```"
      inline: false
    - name: "Bedrock port:"
      value: "```yaml\n19132```"
      inline: false
  avatar: ""
  avatar_url: ""
  image: "https://i.imgur.com/lX19VI7.png"
  thumbnail: ""
  footer: "Last update: %time%"
  footer_icon: ""

offline-embed:
  title: "Server Status"
  timestamp: false
  color: "#ca3931"  # HEX color
  fields:
    - name: "> **Status**"
      value: "```ml\nOffline```"
      inline: true
    - name: "> **Players**"
      value: "```%player_count%```"
      inline: true
    - name: "IP:"
      value: "```onewaycraft.net```"
      inline: false
    - name: "Bedrock port:"
      value: "```yaml\n19132```"
      inline: false
  avatar: ""
  avatar_url: ""
  image: "https://i.imgur.com/kDJ3uCV.png"
  thumbnail: ""
  footer: "Shutdown time: %date% - %time%"
  footer_icon: ""


  # Connection settings, you probably don't have to change anything here!
  # How many times the plugin will try to reconnect to Discord servers if the connection fails
  connection-attempts: 3
  # Time in seconds to wait before trying to reconnect if the connection fails
  reconnect-interval: 5